//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Reflection;
using System.Xml;

namespace NSMk_xaml {

    public class mk_xamlDriver {
        #region constants
        const string CLASS_NAME = "MainWindow";
        const string NAMESPACE = "NSTmp";
        #endregion

        static void windowHandler(object sender, out string elementName, out string fileName, out string nameSpace) {
			elementName = "Window";
			fileName = CLASS_NAME;
			nameSpace = NAMESPACE;
		}

		static void windowElement(object sender, XmlWriter xw) {
			xw.WriteAttributeString("Name", XamlFileGenerator.NS_X, "window1");
			xw.WriteAttributeString("Class", XamlFileGenerator.NS_X, NAMESPACE + "." + CLASS_NAME);
			xw.WriteAttributeString("Title", "MainWindow");
			xw.WriteAttributeString("Width", "350");
			xw.WriteAttributeString("Height", "525");
		}

		static void windowContent(object sender, XmlWriter xw) {
			xw.WriteStartElement("Grid");
			xw.WriteEndElement();
		}

		static void log(MethodBase mb) {
			Debug.Print(mb.ReflectedType.Name + "." + mb.Name);
		}

		[STAThread()]
		public static void Main(string[] args) {
			string xamlName, csName, modelName;

			XamlFileGenerator.generateFile(
				new XamlGenerationHandler(windowHandler),
				new XamlElementAttributeHandler(windowElement),
				new XamlContentHandler(windowContent),
				out xamlName, out csName, out modelName);
		}
	}
}